insert into public.parts_catalog (product_type, category, part_name, position) values
  ('Double Hung', 'Sash', 'Sash - S1 (top)', 'S1 (top)'),
  ('Double Hung', 'Glass / IGU', 'Glass / IGU - S1 (top)', 'S1 (top)'),
  ('Double Hung', 'Sash Lock / Keeper', 'Sash lock - S1 (top)', 'S1 (top)'),
  ('Double Hung', 'Sash', 'Sash - S2 (bottom)', 'S2 (bottom)'),
  ('Double Hung', 'Glass / IGU', 'Glass / IGU - S2 (bottom)', 'S2 (bottom)'),
  ('Double Hung', 'Sash Lock / Keeper', 'Sash lock - S2 (bottom)', 'S2 (bottom)'),
  ('Double Hung', 'Balance', 'Balance - S1 (top)', 'S1 (top)'),
  ('Double Hung', 'Balance', 'Balance - S2 (bottom)', 'S2 (bottom)'),
  ('Double Hung', 'Tilt Latch', 'Tilt latch (pair)', null),
  ('Double Hung', 'Pivot Bar', 'Pivot bar', null),
  ('Double Hung', 'Weatherstrip', 'Weatherstrip', null),
  ('Double Hung', 'Insect Screen', 'Insect screen', null),
  ('Double Hung', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Double Hung', 'Grille', 'Grille (removable)', null),
  ('Double Hung', 'Grille Clip', 'Grille clip', null),
  ('Double Hung', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Double Hung', 'Hardware', 'Hardware / handle set', null),
  ('Casement', 'Sash', 'Sash - Sash', 'Sash'),
  ('Casement', 'Glass / IGU', 'Glass / IGU - Sash', 'Sash'),
  ('Casement', 'Sash Lock / Keeper', 'Sash lock - Sash', 'Sash'),
  ('Casement', 'Operator', 'Operator - Sash', 'Sash'),
  ('Casement', 'Hinge / Arm', 'Hinge arm (pair) - Sash', 'Sash'),
  ('Casement', 'Operator Cover', 'Operator cover', null),
  ('Casement', 'Operator Handle / Crank', 'Operator handle / crank', null),
  ('Casement', 'Lock / Multipoint', 'Sash lock mechanism', null),
  ('Casement', 'Weatherstrip', 'Weatherstrip', null),
  ('Casement', 'Insect Screen', 'Insect screen', null),
  ('Casement', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Casement', 'Grille', 'Grille (removable)', null),
  ('Casement', 'Grille Clip', 'Grille clip', null),
  ('Casement', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Casement', 'Hardware', 'Hardware / handle set', null),
  ('Double Casement', 'Sash', 'Sash - S1 (left)', 'S1 (left)'),
  ('Double Casement', 'Glass / IGU', 'Glass / IGU - S1 (left)', 'S1 (left)'),
  ('Double Casement', 'Sash Lock / Keeper', 'Sash lock - S1 (left)', 'S1 (left)'),
  ('Double Casement', 'Sash', 'Sash - S2 (right)', 'S2 (right)'),
  ('Double Casement', 'Glass / IGU', 'Glass / IGU - S2 (right)', 'S2 (right)'),
  ('Double Casement', 'Sash Lock / Keeper', 'Sash lock - S2 (right)', 'S2 (right)'),
  ('Double Casement', 'Operator', 'Operator - S1 (left)', 'S1 (left)'),
  ('Double Casement', 'Hinge / Arm', 'Hinge arm (pair) - S1 (left)', 'S1 (left)'),
  ('Double Casement', 'Operator', 'Operator - S2 (right)', 'S2 (right)'),
  ('Double Casement', 'Hinge / Arm', 'Hinge arm (pair) - S2 (right)', 'S2 (right)'),
  ('Double Casement', 'Operator Cover', 'Operator cover', null),
  ('Double Casement', 'Operator Handle / Crank', 'Operator handle / crank', null),
  ('Double Casement', 'Lock / Multipoint', 'Sash lock mechanism', null),
  ('Double Casement', 'Weatherstrip', 'Weatherstrip', null),
  ('Double Casement', 'Insect Screen', 'Insect screen', null),
  ('Double Casement', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Double Casement', 'Grille', 'Grille (removable)', null),
  ('Double Casement', 'Grille Clip', 'Grille clip', null),
  ('Double Casement', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Double Casement', 'Hardware', 'Hardware / handle set', null),
  ('Triple Casement', 'Sash', 'Sash - S1 (left)', 'S1 (left)'),
  ('Triple Casement', 'Glass / IGU', 'Glass / IGU - S1 (left)', 'S1 (left)'),
  ('Triple Casement', 'Sash Lock / Keeper', 'Sash lock - S1 (left)', 'S1 (left)'),
  ('Triple Casement', 'Sash', 'Sash - S2 (center)', 'S2 (center)'),
  ('Triple Casement', 'Glass / IGU', 'Glass / IGU - S2 (center)', 'S2 (center)'),
  ('Triple Casement', 'Sash Lock / Keeper', 'Sash lock - S2 (center)', 'S2 (center)'),
  ('Triple Casement', 'Sash', 'Sash - S3 (right)', 'S3 (right)'),
  ('Triple Casement', 'Glass / IGU', 'Glass / IGU - S3 (right)', 'S3 (right)'),
  ('Triple Casement', 'Sash Lock / Keeper', 'Sash lock - S3 (right)', 'S3 (right)'),
  ('Triple Casement', 'Operator', 'Operator - S1 (left)', 'S1 (left)'),
  ('Triple Casement', 'Hinge / Arm', 'Hinge arm (pair) - S1 (left)', 'S1 (left)'),
  ('Triple Casement', 'Operator', 'Operator - S2 (center)', 'S2 (center)'),
  ('Triple Casement', 'Hinge / Arm', 'Hinge arm (pair) - S2 (center)', 'S2 (center)'),
  ('Triple Casement', 'Operator', 'Operator - S3 (right)', 'S3 (right)'),
  ('Triple Casement', 'Hinge / Arm', 'Hinge arm (pair) - S3 (right)', 'S3 (right)'),
  ('Triple Casement', 'Operator Cover', 'Operator cover', null),
  ('Triple Casement', 'Operator Handle / Crank', 'Operator handle / crank', null),
  ('Triple Casement', 'Lock / Multipoint', 'Sash lock mechanism', null),
  ('Triple Casement', 'Weatherstrip', 'Weatherstrip', null),
  ('Triple Casement', 'Insect Screen', 'Insect screen', null),
  ('Triple Casement', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Triple Casement', 'Grille', 'Grille (removable)', null),
  ('Triple Casement', 'Grille Clip', 'Grille clip', null),
  ('Triple Casement', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Triple Casement', 'Hardware', 'Hardware / handle set', null),
  ('Awning', 'Sash', 'Sash - Sash', 'Sash'),
  ('Awning', 'Glass / IGU', 'Glass / IGU - Sash', 'Sash'),
  ('Awning', 'Sash Lock / Keeper', 'Sash lock - Sash', 'Sash'),
  ('Awning', 'Operator', 'Operator - Sash', 'Sash'),
  ('Awning', 'Hinge / Arm', 'Hinge arm (pair) - Sash', 'Sash'),
  ('Awning', 'Operator Cover', 'Operator cover', null),
  ('Awning', 'Operator Handle / Crank', 'Operator handle / crank', null),
  ('Awning', 'Lock / Multipoint', 'Sash lock mechanism', null),
  ('Awning', 'Weatherstrip', 'Weatherstrip', null),
  ('Awning', 'Insect Screen', 'Insect screen', null),
  ('Awning', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Awning', 'Grille', 'Grille (removable)', null),
  ('Awning', 'Grille Clip', 'Grille clip', null),
  ('Awning', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Awning', 'Hardware', 'Hardware / handle set', null),
  ('Gliding Window', 'Sash', 'Sash - S1 (left)', 'S1 (left)'),
  ('Gliding Window', 'Glass / IGU', 'Glass / IGU - S1 (left)', 'S1 (left)'),
  ('Gliding Window', 'Sash Lock / Keeper', 'Sash lock - S1 (left)', 'S1 (left)'),
  ('Gliding Window', 'Sash', 'Sash - S2 (right)', 'S2 (right)'),
  ('Gliding Window', 'Glass / IGU', 'Glass / IGU - S2 (right)', 'S2 (right)'),
  ('Gliding Window', 'Sash Lock / Keeper', 'Sash lock - S2 (right)', 'S2 (right)'),
  ('Gliding Window', 'Roller', 'Sash roller (pair)', null),
  ('Gliding Window', 'Lock', 'Gliding sash lock', null),
  ('Gliding Window', 'Weatherstrip', 'Weatherstrip', null),
  ('Gliding Window', 'Insect Screen', 'Insect screen', null),
  ('Gliding Window', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Gliding Window', 'Grille', 'Grille (removable)', null),
  ('Gliding Window', 'Grille Clip', 'Grille clip', null),
  ('Gliding Window', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Gliding Window', 'Hardware', 'Hardware / handle set', null),
  ('Picture', 'Weatherstrip', 'Weatherstrip', null),
  ('Picture', 'Insect Screen', 'Insect screen', null),
  ('Picture', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Picture', 'Grille', 'Grille (removable)', null),
  ('Picture', 'Grille Clip', 'Grille clip', null),
  ('Picture', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Picture', 'Hardware', 'Hardware / handle set', null),
  ('Bay/Bow', 'Sash', 'Sash - Center', 'Center'),
  ('Bay/Bow', 'Glass / IGU', 'Glass / IGU - Center', 'Center'),
  ('Bay/Bow', 'Sash Lock / Keeper', 'Sash lock - Center', 'Center'),
  ('Bay/Bow', 'Sash', 'Sash - Left flanker', 'Left flanker'),
  ('Bay/Bow', 'Glass / IGU', 'Glass / IGU - Left flanker', 'Left flanker'),
  ('Bay/Bow', 'Sash Lock / Keeper', 'Sash lock - Left flanker', 'Left flanker'),
  ('Bay/Bow', 'Sash', 'Sash - Right flanker', 'Right flanker'),
  ('Bay/Bow', 'Glass / IGU', 'Glass / IGU - Right flanker', 'Right flanker'),
  ('Bay/Bow', 'Sash Lock / Keeper', 'Sash lock - Right flanker', 'Right flanker'),
  ('Bay/Bow', 'Weatherstrip', 'Weatherstrip', null),
  ('Bay/Bow', 'Insect Screen', 'Insect screen', null),
  ('Bay/Bow', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Bay/Bow', 'Grille', 'Grille (removable)', null),
  ('Bay/Bow', 'Grille Clip', 'Grille clip', null),
  ('Bay/Bow', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Bay/Bow', 'Hardware', 'Hardware / handle set', null),
  ('Specialty', 'Sash', 'Sash - Sash', 'Sash'),
  ('Specialty', 'Glass / IGU', 'Glass / IGU - Sash', 'Sash'),
  ('Specialty', 'Sash Lock / Keeper', 'Sash lock - Sash', 'Sash'),
  ('Specialty', 'Weatherstrip', 'Weatherstrip', null),
  ('Specialty', 'Insect Screen', 'Insect screen', null),
  ('Specialty', 'Screen Frame Corner', 'Screen frame corner', null),
  ('Specialty', 'Grille', 'Grille (removable)', null),
  ('Specialty', 'Grille Clip', 'Grille clip', null),
  ('Specialty', 'Jamb Liner / Frame', 'Jamb liner / frame part', null),
  ('Specialty', 'Hardware', 'Hardware / handle set', null),
  ('Gliding Patio Door', 'Panel', 'Panel - Operating panel', 'Operating panel'),
  ('Gliding Patio Door', 'Glass / IGU', 'Glass / IGU - Operating panel', 'Operating panel'),
  ('Gliding Patio Door', 'Panel', 'Panel - Stationary panel', 'Stationary panel'),
  ('Gliding Patio Door', 'Glass / IGU', 'Glass / IGU - Stationary panel', 'Stationary panel'),
  ('Gliding Patio Door', 'Roller', 'Tandem rollers (operating panel)', null),
  ('Gliding Patio Door', 'Roller Adjustment', 'Roller adjustment plug / screw', null),
  ('Gliding Patio Door', 'Handle Set', 'Interior handle set', null),
  ('Gliding Patio Door', 'Handle Set', 'Exterior handle set', null),
  ('Gliding Patio Door', 'Lock', 'Keyed lock cylinder', null),
  ('Gliding Patio Door', 'Lock', 'Reach-out lock', null),
  ('Gliding Patio Door', 'Lock', 'Auxiliary foot lock', null),
  ('Gliding Patio Door', 'Weatherstrip', 'Interlock weatherstrip', null),
  ('Gliding Patio Door', 'Weatherstrip', 'Side-jamb weatherstrip', null),
  ('Gliding Patio Door', 'Sill', 'Sill / sill cap', null),
  ('Gliding Patio Door', 'Frame / Jamb', 'Head / side jamb part', null),
  ('Gliding Patio Door', 'Extension Jamb', 'Extension jamb', null),
  ('Gliding Patio Door', 'Glazing Stop', 'Glazing stop', null),
  ('Gliding Patio Door', 'Insect Screen', 'Insect screen panel', null),
  ('Gliding Patio Door', 'Screen Roller', 'Screen rollers', null),
  ('Gliding Patio Door', 'Screen Lock', 'Screen lock / latch', null),
  ('Gliding Patio Door', 'Grille', 'Grille (removable)', null),
  ('Gliding Patio Door', 'Grille Clip', 'Grille clip', null),
  ('Gliding Patio Door', 'Hardware', 'Hardware trim set', null),
  ('Hinged Patio Door', 'Panel', 'Door panel - Active', 'Active'),
  ('Hinged Patio Door', 'Glass / IGU', 'Glass / IGU - Active', 'Active'),
  ('Hinged Patio Door', 'Panel', 'Door panel - Passive', 'Passive'),
  ('Hinged Patio Door', 'Glass / IGU', 'Glass / IGU - Passive', 'Passive'),
  ('Hinged Patio Door', 'Panel', 'Door panel - Stationary', 'Stationary'),
  ('Hinged Patio Door', 'Glass / IGU', 'Glass / IGU - Stationary', 'Stationary'),
  ('Hinged Patio Door', 'Panel Rail / Stile', 'Top rail / bottom rail / side stile', null),
  ('Hinged Patio Door', 'Glass Stop', 'Glass stop', null),
  ('Hinged Patio Door', 'Hinge', 'Hinge', null),
  ('Hinged Patio Door', 'Lock Mechanism', 'Multipoint lock mechanism - active', null),
  ('Hinged Patio Door', 'Lock Mechanism', 'Multipoint lock mechanism - passive', null),
  ('Hinged Patio Door', 'Hook / Flush / Latch Bolt', 'Hook bolt / flush bolt / latch bolt', null),
  ('Hinged Patio Door', 'Keyed Lock', 'Keyed lock cylinder', null),
  ('Hinged Patio Door', 'Handle Set', 'Handle trim set', null),
  ('Hinged Patio Door', 'Weatherstrip', 'Weatherstrip', null),
  ('Hinged Patio Door', 'Sill', 'Sill / drop-nose kit', null),
  ('Hinged Patio Door', 'Frame / Jamb', 'Head / side jamb part', null),
  ('Hinged Patio Door', 'Astragal', 'Astragal (double door)', null),
  ('Hinged Patio Door', 'Insect Screen', 'Insect screen / gliding screen', null),
  ('Hinged Patio Door', 'Grille', 'Grille (removable)', null),
  ('Hinged Patio Door', 'Grille Clip', 'Grille clip', null),
  ('Hinged Patio Door', 'Hardware', 'Hardware trim set', null),
  ('Entry Door', 'Slab / Panel', 'Door slab - Active', 'Active'),
  ('Entry Door', 'Glass Insert', 'Decorative glass insert - Active', 'Active'),
  ('Entry Door', 'Slab / Panel', 'Door slab - Inactive', 'Inactive'),
  ('Entry Door', 'Glass Insert', 'Decorative glass insert - Inactive', 'Inactive'),
  ('Entry Door', 'Hinge', 'Hinge', null),
  ('Entry Door', 'Lockset', 'Lockset / latch', null),
  ('Entry Door', 'Deadbolt', 'Deadbolt', null),
  ('Entry Door', 'Handleset', 'Handleset', null),
  ('Entry Door', 'Multipoint Lock', 'Multipoint lock mechanism', null),
  ('Entry Door', 'Weatherstrip', 'Weatherstrip', null),
  ('Entry Door', 'Sweep', 'Door sweep / bottom', null),
  ('Entry Door', 'Sill / Threshold', 'Sill / threshold', null),
  ('Entry Door', 'Frame / Jamb', 'Head / side jamb part', null),
  ('Entry Door', 'Astragal', 'Astragal (double door)', null),
  ('Entry Door', 'Sidelite', 'Sidelite glass / part', null),
  ('Entry Door', 'Transom', 'Transom glass / part', null),
  ('Entry Door', 'Grille', 'Grille (removable)', null),
  ('Entry Door', 'Hardware', 'Hardware / trim', null),
  ('Storm Door', 'Handle Set', 'Handle set', null),
  ('Storm Door', 'Closer', 'Closer (pneumatic)', null),
  ('Storm Door', 'Sweep', 'Sweep / bottom expander', null),
  ('Storm Door', 'Hinge Rail', 'Hinge rail', null),
  ('Storm Door', 'Glass Panel', 'Glass panel / insert', null),
  ('Storm Door', 'Screen Panel', 'Screen panel / insert', null),
  ('Storm Door', 'Latch', 'Latch / strike', null),
  ('Storm Door', 'Latch Housing', 'Latch housing', null),
  ('Storm Door', 'Retractable Screen Housing', 'Retractable screen housing', null),
  ('Storm Door', 'Screen Track', 'Retractable screen track', null),
  ('Storm Door', 'Sill Adapter', 'Sill adapter', null),
  ('Storm Door', 'Glide', 'Glide', null),
  ('Storm Door', 'Frame / Z-bar', 'Z-bar / mounting frame', null),
  ('Storm Door', 'Hardware', 'Hardware / fasteners', null);
